Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/attica' : '@same'
    'frameworks/ki18n' : '@same'
    'frameworks/kitemviews' : '@same'
    'frameworks/karchive' : '@same'
    'frameworks/kiconthemes' : '@same'
    'frameworks/ktextwidgets' : '@same'
    'frameworks/kxmlgui' : '@same'
    'frameworks/solid' : '@same'
    'frameworks/kbookmarks' : '@same'
    'frameworks/kio' : '@same'
    'frameworks/kirigami' : '@same'
    'frameworks/kpackage' : '@same'
    'frameworks/syndication' : '@same'

Options:
  test-before-installing: True
