# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/attica' : '@same'
    'frameworks/ki18n' : '@same'
    'frameworks/kitemviews' : '@same'
    'frameworks/karchive' : '@same'
    'frameworks/kio' : '@same'

Options:
  test-before-installing: True
